#!/bin/sh

ENABLED=yes

DESC="Asterisk server"
PROCS="asterisk"
PROG="/opt/sbin/$PROCS"

start_pre() {
  dbdir="/opt/var/lib/$PROCS/astdb"
  logdir="/opt/var/log/$PROCS"
  cdrcsvdir="$logdir/cdr-csv"
  rundir="/opt/var/run/$PROCS"
  spooldir="/opt/var/spool/$PROCS"
  varlibdir="/opt/var/lib/$PROCS"

  for i in \
    "$logdir" \
    "$cdrcsvdir" \
    "$rundir" \
    "$spooldir" \
    "$varlibdir" \
    "$dbdir"
  do
    if ! [ -e "$i" ]; then
      mkdir -pm 0750 "$i"
      [ -d "$i" ] && chown "$PROCS":"$PROCS" "$i"
    fi
  done
}

PRECMD="start_pre"
ARGS="-U $PROCS"
PREARGS=""

. /opt/etc/init.d/rc.func
